deploy/chocolatey/tools/VERIFICATION, pack.ps1
* In pack.ps1 hash in uppercase.
* Removed VERIFICATION from Chocolatye package after comment from Chocolatey moderator
=> Small changes for Chocolatey package

src/DocLinkChecker/Helpers/ExitCodeHelper.cs, src/DocLinkChecker/Program.cs, src/DocLinkChecker/README.md
- Improve error code return
- Improve table check when separator is used ( | example `| somethinghere` |), previously would find 3 separators while only 2 are really used
=> Improvement for DocLinkChecker

src/DocFxOpenApi/DocFxOpenApi.cs, src/DocFxOpenApi/DocFxOpenApi.csproj, src/DocFxOpenApi/DocFxOpenApi.sln, src/DocFxOpenApi/Domain/CommandlineOptions.cs, src/DocFxOpenApi/GlobalSuppressions.cs, src/DocFxOpenApi/Helpers/MessageHelper.cs, src/DocFxOpenApi/NuGet.Config, src/DocFxOpenApi/README.md
This DocFxOpenAPI tool converts existing OpenAPI specification files into the format compatible with DocFX (OpenAPI v2 JSON files). It's now part of the docfx-companion-tools package. Please see the README in the source folder of the DocFxOpenAPI tool for more information on how to use it.
=> Added OpenAPI tool

src/DocFxTocGenerator/TocGenerator.cs
We filtered out INDEX.md from the list of files in a folder. This resulted in skipping the processing of existing INDEX.md files in the order or the TOC. Removed that filter from the query.
=> FIX: removed filter on INDEX.md to process existing ones

src/DocLinkChecker/Program.cs
**DocLinkChecker**
* Excluded ftp, ftps, xref and mailto protocols from link validation
* Removed check for link containing @ sign to recognize email address. Covered by check for mailto protocol
=> Excluded ftp, xref and mailto protocols from validation.

src/DocLinkChecker/DocLinkChecker/App.cs
If you have no errors or warnings the tool would incorrectly exit with a code of -1 rather than 0
=> Fix: Success Code on 0 errors and warnings

src/DocLinkChecker/DocLinkChecker/DocLinkChecker.csproj
Build error was generating while adding SelfContained and UseAppHostin the csproj which are not compatible with each others.
=> Fixing packing for DocLinkChecker

src/DocLinkChecker/DocLinkChecker/Program.cs, src/DocLinkChecker/DocLinkChecker/Services/CrawlerService.cs, src/DocLinkChecker/DocLinkChecker/Services/LinkValidatorService.cs, src/DocLinkChecker/DocLinkChecker/Services/ResourceValidatorService.cs
I changed some logging to use standard spacing.
Also changed logging in CrawlerService and ResourceValidatorService to further investigate the error "Length cannot be less than zero" that pops up now and then. Those errors are now ignored, but in verbose mode a stack trace is shown to further investigate the scenario which is causing these errors (and where).
=> Small logging changes.

src/DocLinkChecker/DocLinkChecker/Helpers/MarkdownHelper.cs
Checking for available line-ending characters to prevent error in indexing.
=> Fix the length error in DocLinkChecker

src/DocLanguageTranslator/Program.cs
Fix additional space created during translation when an exclamation mark is used
fix #44
=> Fix additional space created during translation when an exclamation mark is used

src/DocLinkChecker/DocLinkChecker.Test/Helpers/MarkdownExtensions.cs, src/DocLinkChecker/DocLinkChecker.Test/HyperlinkTests.cs, src/DocLinkChecker/DocLinkChecker.Test/MarkdownTests.cs, src/DocLinkChecker/DocLinkChecker/Helpers/MarkdownHelper.cs, src/DocLinkChecker/DocLinkChecker/Properties/launchSettings.json
Added support for the use of UNICODE characters like á or ö in markdown headings.
=> Doclinkchecker unicode fix

src/DocFxTocGenerator/README.md
Changed the tool name in the DocFxTocGenerator reamde, to match the tool name in the main readme.
Otherwise the shown command does not work with the newest version.
=> Change tool name in documentation readme of DocFxTocGenerator

src/DocFxOpenApi/DocFxOpenApi.cs, src/DocFxOpenApi/Domain/CommandlineOptions.cs, src/DocFxOpenApi/README.md
The current version has a problem that it does not support a single file to be specified as the source - only a folder.
If the source folder has more than one .json or .yml file the program will try to parse them all, throwing errors in the output.
This change introduces the support for a single file to be passed as source for the conversion.
=> Added support to specify a single source file

.gitignore, src/DocFxTocGenerator/TocGenerator.cs
When a folder has only one markdown document it is automatically picked as entry point for the folder, unless the option `--index` is used to generate an index as well. In that case the generated `index.md` wasn't picked as entry point. With this fix issue #27 is solved.
=> Fixed issue with ignoring generated index.md in folder with 1 file

src/DocLinkChecker/DocLinkChecker.Test/HyperlinkTests.cs, src/DocLinkChecker/DocLinkChecker/Models/Hyperlink.cs, src/DocLinkChecker/DocLinkChecker/Services/LinkValidatorService.cs
DocFx supports the use of a ~ to reference the folder where the docfx.json resides. See [documentation of DocFx](https://dotnet.github.io/docfx/docs/links-and-cross-references.html#link-to-local-files). As we have no knowledge of that file in the DocLinkChecker, we assume that the docfx.json file is in the document root.
With this PR we added the support for the use of ~ to reference the documentation root folder, and we validate if the reference file exists. This test will fail of course if the docfx.json is in another directory.
This PR fixes #50.
=> Added validation of root-reference with ~

src/DocLinkChecker/DocLinkChecker.Test/HyperlinkTests.cs, src/DocLinkChecker/DocLinkChecker.Test/MockFileService.cs, src/DocLinkChecker/DocLinkChecker/Models/Hyperlink.cs, src/DocLinkChecker/DocLinkChecker/Services/LinkValidatorService.cs
Add basic support for `%20` in url. See #60 for details.
Was hoping for a more elegant implementation. But this works.
Fixes #60
=> DocLinkChecker: Support for %20 in links

src/DocFxOpenApi/DocFxOpenApi.cs, src/DocFxOpenApi/Domain/CommandlineOptions.cs, src/DocFxOpenApi/Helpers/MessageHelper.cs
* Usings outside namespace
* Proper formatting of new()
* Tuple variables need camel casing
=> DocFxOpenApi: Changes for new rules with .NET8. No logic changes.

src/DocLanguageTranslator/Domain/CommandlineOptions.cs, src/DocLanguageTranslator/Domain/ErrorDetail.cs, src/DocLanguageTranslator/Domain/ErrorResponse.cs, src/DocLanguageTranslator/Domain/Translation.cs, src/DocLanguageTranslator/Domain/TranslationResults.cs, src/DocLanguageTranslator/Helpers/MessageHelper.cs, src/DocLanguageTranslator/MarkdownTransformRenderer.cs, src/DocLanguageTranslator/Program.cs, src/DocLanguageTranslator/ReplacementRenderer.cs
* Usings outside namespace
* Proper formatting of new()
* Tuple variables need camel casing
=> DocLanguageTranslator: Changes for new rules with .NET8. No logic changes.

src/DocFxTocGenerator/DocFxTocGenerator.Test/ConfigFilesServiceTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/ContentInventoryActionTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/EnsureIndexActionTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/FileInfoServiceTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/GenerateTocActionTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/Helpers/MockFileService.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/IndexServiceTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/LiquidServiceTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/TableOfContentsServiceTests.cs, src/DocFxTocGenerator/DocFxTocGenerator/Actions/ContentInventoryAction.cs, src/DocFxTocGenerator/DocFxTocGenerator/Actions/EnsureIndexAction.cs, src/DocFxTocGenerator/DocFxTocGenerator/ConfigFiles/ConfigFilesService.cs, src/DocFxTocGenerator/DocFxTocGenerator/FileService/FileInfoService.cs, src/DocFxTocGenerator/DocFxTocGenerator/Program.cs, src/DocFxTocGenerator/DocFxTocGenerator/README.md
DocFxTocGenerator has a new option to output all titles in camelCase. If this option is not used, the already used PascalCase is used for titles. Only exception are titles coming from `.override` files.
Tests and documentation was modified for this change as well.
This closes #54
=> DocFxTocGenerator: added camelCase option

.github/workflows/build.yml, .github/workflows/release-and-publish.yml
Updated:
* Gitversion setup and execute to use v3.0.0 (latest)
* Dotnet v4 for 8.x
* Checkout v4
=> Updated pipelines for new action versions

src/DocLinkChecker/README.md
Return codes 1000 and 1001 are truncated to bytes on (most) Linux systems. To be backwards compatible the documentation is modified to indicate the values on Linux systems.
This closes #63
=> Modified documentation for return codes of DocLinkChecker on Linux

src/DocFxTocGenerator/DocFxTocGenerator.Test/ContentInventoryActionTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/Helpers/MockFileService.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/TableOfContentsServiceTests.cs, src/DocFxTocGenerator/DocFxTocGenerator/Actions/ContentInventoryAction.cs, src/DocFxTocGenerator/DocFxTocGenerator/Program.cs, src/DocFxTocGenerator/DocFxTocGenerator/README.md
Was not implemented, now it is. So this closes #75
=> DocFxTocGenerator: fixed folder override

src/DocFxTocGenerator/DocFxTocGenerator.Test/GenerateTocActionTests.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/Helpers/MockFileService.cs, src/DocFxTocGenerator/DocFxTocGenerator.Test/TableOfContentsServiceTests.cs, src/DocFxTocGenerator/DocFxTocGenerator/Actions/ContentInventoryAction.cs, src/DocFxTocGenerator/DocFxTocGenerator/FileService/FileInfoService.cs, src/DocFxTocGenerator/DocFxTocGenerator/FileService/FolderFileBase.cs, src/DocFxTocGenerator/DocFxTocGenerator/TableOfContents/TableOfContentsService.cs
Introduced a bool to track if we have an override of the DisplayName. For folders we use this to make sure we're not taking the title from the Index or ReadMe when indicated by the --folderRef. Override always must take preference.
Also added a test for this issue and modified others because of this improved behavior.
This closes #77
=> DocFxTocGenerator: Fixed override for folders to be used over index or readme

src/DocLinkChecker/DocLinkChecker.Test/HyperlinkTests.cs, src/DocLinkChecker/DocLinkChecker/Services/LinkValidatorService.cs
Handles different path separators in Linux and Windows, where Windows can have \ and /. Added path normalization on comparison. Also added test for this issue.
Solves #81
=> DocLinkChecker: Normalize-path on heading validation

src/DocFxTocGenerator/DocFxTocGenerator.Test/GenerateTocActionTests.cs, src/DocFxTocGenerator/DocFxTocGenerator/Actions/ContentInventoryAction.cs, src/DocFxTocGenerator/DocFxTocGenerator/FileService/FileInfoService.cs
Ordering files and folders using .order files didn't work properly. Folders were not ordered following .order definition. That is fixed now. Added tests to simulate the problem and validate the fix.
This closes #86
=> DocFxTocGenerator: fixed ordering of folders

src/DocAssembler/DocAssembler.Test/IssueTests.cs, src/DocAssembler/DocAssembler/Actions/InventoryAction.cs
When a markdown file has a reference like `(topic)[#topic)`, it crashed the tool. That is properly handled now including a unit test to validate.
This closes #89
=> Fixed handling of heading references in the same file

.gitignore, src/DocLinkChecker/DocLinkChecker.Test/MarkdownTests.cs, src/DocLinkChecker/DocLinkChecker/Helpers/MarkdownHelper.cs
Underscore is now kept in link to header with underscore in text.
=> Fixed issue #95. Validated with test
